# version: '3.8' 

services:
  db:
    image: postgres:15 
    container_name: nestjs_postgres_dev 
    restart: unless-stopped 
    environment:
      POSTGRES_USER: ${DB_USERNAME} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data in a named volume

volumes:
  postgres_data:
    driver: local