version: '3.8'

services:
  app:
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3000}
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
