FROM node:22-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm install

RUN npm install -g ts-node-dev

COPY . .

ENV NODE_ENV=development
ENV PORT=3000

EXPOSE 3000

CMD ["ts-node-dev", "--respawn", "--transpile-only", "src/main.ts"]
